services:
  octopus:
    image: tugboatqa/debian
    default: true
    expose: 5002
    depends:
      - buffalo
    commands:
      init:
        - /bin/bash ${TUGBOAT_ROOT}/octopus/scripts/provision.sh
      build:
        - cd ${TUGBOAT_ROOT}/octopus && /bin/bash ./scripts/build.sh
      start:
        - npm run start &

  buffalo:
    image: tugboatqa/debian
    checkout: true
    commands:
      init:
        - /bin/bash ${TUGBOAT_ROOT}/buffalo/scripts/provision.sh
      build:
        - cd ${TUGBOAT_ROOT}/buffalo && /bin/bash ./scripts/build.sh
      start:
        - npm run start &
